# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit
language: en-US
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    # Review Dependabot PRs too (dependency audit)
    ignore_title_keywords: []
    drafts: false
chat:
  auto_reply: true
